name: Build Windows Binaries

on:
  push:
    branches: [ "master", "feature/*" ]
    tags: ["*"]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-arch: ["386", "amd64"]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        cache: true
    - name: Install Go dependencies
      run: go install
    - name: Build ${{ matrix.go-arch }} Windows executable
      env:
        GOOS: windows
        GOARCH: ${{ matrix.go-arch }}
      run: go build -v -o tut_${{ matrix.go-arch }}.exe
    - name: Upload build output
      uses: actions/upload-artifact@v3
      with:
        name: tut_${{ matrix.go-arch }}
        path: tut_${{ matrix.go-arch }}.exe
